[package]
name="demos"
version="0.1.0"
author= ["experience iq <ayeje@aj.gmail.com>"]
edition = "2020"

[dependencies]
humantime = "2.0.1"
chrono = "0.4.15"


[lib]
name = "activity"
path = "src/mylib.rs"